### ISSUE TITLE
type(elem) == RepeatedScalarFieldContainer: 

### ISSUE THREAD

**Issue by puneetvaza** [ssudholt/phocnet#2]
Traceback (most recent call last):
  File "/home/cerelabs/Softwares/eclipse/plugins/org.python.pydev_5.2.0.201608171824/pysrc/pydevd.py", line 1531, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/cerelabs/Softwares/eclipse/plugins/org.python.pydev_5.2.0.201608171824/pysrc/pydevd.py", line 938, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/cerelabs/puneet/eclipse-ws/phoc/tools/train_phocnet.py", line 61, in <module>
    PHOCNetTrainer(**params).train_phocnet()
  File "/home/cerelabs/puneet/phocnet-master/lib/python2.7/site-packages/phocnet/training/phocnet_trainer.py", line 195, in train_phocnet
    weight_decay=self.weight_decay)
  File "/home/cerelabs/puneet/phocnet-master/lib/python2.7/site-packages/phocnet/caffe/solver_proto_generator.py", line 21, in generate_solver_proto
    setattr(sp, k, v)
TypeError: Can't set composite field

>>>type(elem) == RepeatedScalarFieldContainer:
 code is expecting RepeatedScalarFieldContainer but its getting **RepeatedScalarContainer**

**Comment by ssudholt** [comment]
Are you using the custom Caffe version or the standard one?

**Comment by puneetvaza** [comment]
yes custom which you supplied

**Comment by adiprnm** [comment]
I've got the same error. I've search the solution but I could't find the right one. Any solutions?

**Comment by lvbeltranb** [comment]
I also got the same error, does anybody have any solution? Thanks
